#!/usr/bin/env python

import functools
import argparse
import subprocess as sp

def call_process(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        try:
            output = func(*args, **kwargs)
            result = parse_output(output)
            on_success(result)
        except sp.CalledProcessError as error:
            on_failure(error)
    return wrapper

def parse_arguments():
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('query', nargs='+', help='')
    return parser.parse_args()

def on_failure(error):
    print("ERROR")

def on_success(value):
    print(value)

def parse_output(output):
    count = int(output)
    return count if count > 0 else ""

@call_process
def execute(args):
    command = ["notmuch", "count", *args]
    return sp.check_output(command, text=True, stderr=sp.STDOUT)

if __name__ == "__main__":
    arguments = parse_arguments()
    execute(arguments.query)

